def irregular_verbs(): 
    list_verbs = {
        'be': 'was/were', 
    'become': 'became',  
    'begin': 'began', 
    'bite': 'bit',   
    'blow': 'blew',  
    'break': 'broke',   
    'bring': 'brought',   
    'build': 'built',
    'burn': 'burnt', 
    'buy': 'bought', 
    'catch': 'caught',  
    'choose': 'chose', 
    'come': 'came', 
    'cut' :'cut', 
    'do' : 'did', 
    'draw': 'drew',  
    'dream': 'dreamt', 
    'drive' : 'drove', 
    'drink': 'drank', 
    'eat': 'ate', 
    'fall':'fell',
    'feel': 'felt', 
    'fight': 'fought', 
    'find': 'found', 
    'fly': 'flew', 
    'forbid': 'forbade',
    'forgive': 'forgave', 
    'freeze': 'froze',  
    'get': 'got',
    'give': 'gave', 
    'go': 'went', 
    'grow': 'grew', 
    'hang': 'hung', 
    'hear': 'heard',
    'hide': 'hid',  
    'hit': 'hit',
    'hold': 'held', 
    'hurt' : 'hurt',
    'keep' : 'kept', 
    'know' : 'knew', 
    'lay': 'laid', 
    'leave': 'left', 
    'lend': 'lent', 
    'lie': 'lay', 
    'lose': 'lost', 
    'make': 'made', 
    'mean': 'meant', 
    'meet': 'met', 
    'pay': 'paid', 
    'put': 'put', 
    'read': 'read', 
    'ride': 'rode', 
    'ring': 'rang', 
    'rise': 'rose', 
    'run': 'ran', 
    'say': 'said', 
    'see': 'saw', 
    'seek': 'sought', 
    'sell': 'sold',
    'send': 'sent', 
    'shake': 'shook',
    'shoot': 'shot', 
    'sing': 'sang', 
    'sit': 'sat',
    'sleep' : 'slept',  
    'speak': 'spoke',  
    'spend': 'spent', 
    'steal': 'stole',  
    'swim': 'swam',  
    'swing': 'swung', 
    'take': 'took', 
    'teach': 'taught',  
    'tell' :'told', 
    'think' : 'thought', 
    'throw': 'threw', 
    'understand': 'understood', 
    'wake': 'woke',  
    'wear' :'wore', 
    'win' :'won',
    'write': 'wrote'
        }

    return list_verbs


